services:
  web-app:
    user: "${USER}"
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./core:/core
    environment:
      - DB_NAME=db.sqlite3
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - redis

  redis:
    image: redis:7.0.5-alpine
    hostname: redis
